spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
